# version: '3.8'

services:
  # PostgreSQL Database - Production Secured
  postgres:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    ports: []  # Remove port exposure for security
    networks:
      - backend-network

  # Redis Cache - Production Secured  
  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    ports: []  # Remove port exposure for security
    networks:
      - backend-network

  backend:
    environment:
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-https://gameapp.games}
      API_BASE_URL: ${API_BASE_URL:-https://gameapp.games}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://gameapp.games}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    ports: []  # Remove port exposure for security

  frontend:
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${API_BASE_URL:-https://gameapp.games}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-gameapp.games}
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

networks:
  backend-network:
    driver: bridge
    internal: true  # Isolate backend services
  frontend-network:
    driver: bridge