apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: humor-game-project
  namespace: argocd
spec:
  description: Humor Memory Game Application Project
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/yourusername/game-app-laptop-demo.git'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: humor-game
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  
  # Allowed Kubernetes resources
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
  
  # Allowed namespaced resources
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule
  
  # Sync windows (optional - for production deployments)
  syncWindows:
    - name: allow-all
      schedule: '0 0 * * *'
      duration: 24h
      applications:
        - '*'
      namespaces:
        - '*'
      clusters:
        - '*'
      manualSync: true
