apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: humor-memory-game
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: humor-memory-game
    team: game-dev
spec:
  project: humor-game-project
  source:
    repoURL: https://github.com/yourusername/game-app-laptop-demo.git
    targetRevision: HEAD
    path: k8s
    # Optional: Use a specific branch or tag
    # targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: humor-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
        - /spec/currentReplicas
    - group: ''
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
  # Health checks
  health:
    # Custom health check for the game application
    custom:
      - group: argoproj.io
        kind: Application
        name: humor-memory-game
        namespace: argocd
        health:
          status: Healthy
          message: "All game components are running successfully"
