apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: humor-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: localhost:5001/humor-game/backend:v1.0.0
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: API_PORT
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: humor-game-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: humor-game-secrets
                  key: REDIS_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: humor-game-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: CORS_ORIGIN
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: FRONTEND_URL
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: humor-game-config
                  key: API_BASE_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: humor-game
spec:
  selector:
    app: backend
  ports:
    - port: 3001

