apiVersion: v1
kind: ConfigMap
metadata:
  name: humor-game-config
  namespace: humor-game
data:
  NODE_ENV: "development"
  DB_NAME: "humor_memory_game"
  DB_USER: "gameuser"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  API_PORT: "3001"
  # Production domain - update these for your domain
  CORS_ORIGIN: "http://localhost:8080,https://gameapp.games"
  FRONTEND_URL: "https://gameapp.games"
  API_BASE_URL: "https://gameapp.games"

